# Generated by Django 6.0.3 on 2026-03-31 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detector', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='detectionhistory',
            name='detection_summary',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
